# Generated by Django 6.0.2 on 2026-02-05 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cvs/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('contact_score', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('missing_elements', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cv_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.cvupload')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
